let PostrefrigerationIsActive= new OperationalTimer(120000);
let PostlubricationIsActive= new OperationalTimer(60000); 
let Tecjet = new PIDLoop(0,3,0.5,0,false);//Apertura de la Tecjet en función de Lambda.
let HideTecJet = new PIDLoop(0,3,0.5,0,false);//Apertura de la Tecjet en función de p2'.
let ThrottleValveIdle = new PIDLoop(0,0.450,0.02,0.05,true);
let ThrottleValvePower = new PIDLoop(0,0.1,0.15, 0.1,true);
let Turbobypass = new PIDLoop(0,0.2,0.02,0.05,false);
let GasType=1;
let SetPointChargePressure;
let PowerReduction = "none";
//
let KnobSyncronization = new KNOBS(820,586,1);
let KnobDemand = new KNOBS(742,586,1);
let KnobRequest = new KNOBS(667,586,0);
//
let _Actual=50;
let _Eq=[50,48,45,45,45];
let _Speed=0.001;
let _MaxNoise=[2,4,3,3,4];
let _NoiseOffset=0.68;
let ChargeTemperature = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
//
_Actual=1;
_Eq=[1,0.98,0.92,0.92,0.92];
_Speed=0.001;
_MaxNoise=[0.02,0.03,0.03,0.05,0.05];
_NoiseOffset=0.43;
let ChargePressure = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
//
_Actual=50;
_Eq=[45,52,57,63,70];
_Speed=0.01;
_MaxNoise=[1,2,3,3,3];
_NoiseOffset=0.12;
let PrimaryWaterTemperatureBeforeEngine = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
//
_Actual=50;
_Eq=[45,52,57,63,70];
_Speed=0.01;
_MaxNoise=[1,2,3,3,3];
_NoiseOffset=0.32;  
let PrimaryWaterTemperatureAfterEngine = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
//
_Actual=50;
_Eq=[45,52,57,63,70];
_Speed=0.0001;
_MaxNoise=[1,2,3,3,3];
_NoiseOffset=0.54;
let PrimaryWaterTemperature = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
//
_Actual=1.29;
_Eq=[1.25,1.32,1.45,1.50,1.55];
_Speed=0.01;
_MaxNoise=[0.02,0.03,0.03,0.04,0.04];
_NoiseOffset=0.02;
let PrimaryWaterPressure = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
//
_Actual=0;
_Eq=[0,0,173,1500,1500];
_Speed=0.05;
_MaxNoise=[0,1,2,2,3];
_NoiseOffset=0.07;
let Velocity = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
//
_Actual=35;
_Eq=[35,52,63,83,90];
_Speed=0.0005;
_MaxNoise=[1,2,3,3,4];
_NoiseOffset=0.07;
let OilTemperature = new OperationalVariable(_Actual , _Eq, _Speed, _MaxNoise,_NoiseOffset);
//
_Actual=0;
_Eq=[0,1.34,4.8,3.8,3.8];
_Speed=0.01;
_MaxNoise=[0.05,0.08,0.2,0.2,0.2];
_NoiseOffset=1.34;
let OilPressure = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
//
_Actual=0;
_Eq=[0,0,0,0,0];
_Speed=0.1;
_MaxNoise=[0,0,0,10,10];
_NoiseOffset=0.96;
let ElectricIa = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
//
_Actual=400;
_Eq=[400,400,400,400,400];
_Speed=0.01;
_MaxNoise=[0,0,0.3,0.3,0.3];
_NoiseOffset=0.7;
let ElectricUa = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
//
_Actual=0;
_Eq=[0,0,0,0,0];
_Speed=0.03;
_MaxNoise=[0,0,0,5,5];
_NoiseOffset=0.64;
let ElectricPa = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
//
_Actual=0;
_Eq=[0,0,0,0,0];
_Speed=0.03;
_MaxNoise=[0,0,0,3,3];
_NoiseOffset=0.34;
let ElectricQa = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
//
_Actual=0;
_Eq=[0,0,0,0,0];
_Speed=0.03;
_MaxNoise=[0,0,0,3,3];
_NoiseOffset=0.29;
let ElectricSa = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
//
_Actual=50;
_Eq=[50,50,50,50,50];
_Speed=0.001;
_MaxNoise=[0,0,0,0.5,0.5];
_NoiseOffset=0.51;
let Electricf = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
//
_Actual=0;
_Eq=[0,0,0.8,0.95,0.95];
_Speed=0.001;
_MaxNoise=[0,0,0,0.03,0.03];
_NoiseOffset=0.94;
let ElectricCosPhi = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
//
_Actual=0;
_Eq=[0,0,0,0,900];
_Speed=0.1;
_MaxNoise=[0,0,0,10,10];
_NoiseOffset=0.69;
let ElectricI1 = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
//
_Actual=0;
_Eq=[0,0,0,0,900];
_Speed=0.1;
_MaxNoise=[0,0,0,10,10];
_NoiseOffset=0.59;
let ElectricI2 = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
//
_Actual=0;
_Eq=[0,0,0,0,900];
_Speed=0.1;
_MaxNoise=[0,0,0,10,10];
_NoiseOffset=0.49;
let ElectricI3 = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
//
let ElectricI1max = 0;
let ElectricI2max = 0;
let ElectricI3max = 0;
let ElectricInmax = 0;
let ElectricPmax = 0;
//
_Actual=0;
_Eq=[0,0,400,400,400];
_Speed=0.1;
_MaxNoise=[0,0,0.3,0.3,0.3];
_NoiseOffset=3;
let ElectricU12 = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
//
_Actual=0;
_Eq=[0,0,400,400,400];
_Speed=0.1;
_MaxNoise=[0,0,0.3,0.3,0.3];
_NoiseOffset=2.87;
let ElectricU23 = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
//
_Actual=0;
_Eq=[0,0,400,400,400];
_Speed=0.1;
_MaxNoise=[0,0,0.3,0.3,0.3];
_NoiseOffset=2.61;
let ElectricU31 = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
//
_Actual=0;
_Eq=[0,0,0,290,290];
_Speed=0.1;
_MaxNoise=[0,0,0.3,0.3,0.3];
_NoiseOffset=3.45;
let ElectricU1N = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
//
_Actual=0;
_Eq=[0,0,0,290,290];
_Speed=0.1;
_MaxNoise=[0,0,0.3,0.3,0.3];
_NoiseOffset=0.87;
let ElectricU2N = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
//
_Actual=0;
_Eq=[0,0,0,290,290];
_Speed=0.1;
_MaxNoise=[0,0,0.3,0.3,0.3];
_NoiseOffset=0.84;
let ElectricU3N = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
//
_Actual=0;
_Eq=[0,0,0,0,0];
_Speed=0.1;
_MaxNoise=[0,0,0.3,0.3,0.3];
_NoiseOffset=0.67;
let ElectricIn = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
//
_Actual=0;
_Eq=[0,0,0,1,3];
_Speed=0.1;
_MaxNoise=[0,0,0.3,0.3,0.3];
_NoiseOffset=0.39;
let ElectricUe = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
//
_Actual=0;
_Eq=[0,0,0,0.8,0.6];
_Speed=0.1;
_MaxNoise=[0,0,0.3,0.1,0.1];
_NoiseOffset=0.77;
let ElectricIaDyn = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
//
_Actual=0;
_Eq=[0,0,0,0,0];
_Speed=0.1;
_MaxNoise=[0,0,0.3,0.1,0.1];
_NoiseOffset=0.61;
let ElectricIunbal = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
//
_Actual=25;
_Eq=[28,33,43,55,63];
_Speed=0.01;
_MaxNoise=[1,2,3,3,3];
_NoiseOffset=0.81;
let ElectricWinding1 = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
//
_Actual=25;
_Eq=[28,33,43,55,63];
_Speed=0.01;
_MaxNoise=[1,2,3,3,3];
_NoiseOffset=0.33;
let ElectricWinding2 = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
//
_Actual=25;
_Eq=[28,33,43,55,63];
_Speed=0.01;
_MaxNoise=[1,2,3,3,3];
_NoiseOffset=0.41;
let ElectricWinding3 = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
//
_Actual=25;
_Eq=[28,29,30,35,43];
_Speed=0.001;
_MaxNoise=[1,2,3,3,3];
_NoiseOffset=0.94;
let ElectricBearingDE = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
//
_Actual=25;
_Eq=[28,29,30,35,43];
_Speed=0.001;
_MaxNoise=[1,2,3,3,3];
_NoiseOffset=0.34;
let ElectricBearingNDE = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
//
_Actual=1.35;
_Eq=[1.35,1.5,1.5,1.5,1.75];
_Speed=0.1;
_MaxNoise=[0,0,0.02,0.02,0.02];
_NoiseOffset=0.18;
let Lambda = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
//
let GASmbar=1000;
let GASmbarAfterTecjet=1000;
let GASTemperature=30;
let GASFlow=0;
let GASIdealFlow=0;
let GASDeltaPressure=0;
//
_Actual=25;
_Eq=[28,29,30,31,33];
_Speed=0.03;
_MaxNoise=[3,3,5,5,5];
_NoiseOffset=0.51;
let AmbientTemperature = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
//
let IgnitionPoint=[];
_Actual=24;
_Eq=[0,20,20,24,24];
_Speed=0.005;
_MaxNoise=[0,0,0,0,0];
_NoiseOffset=0.71;
IgnitionPoint[1] = new OperationalVariable(_Actual,_Eq, _Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.34;
IgnitionPoint[2] = new OperationalVariable(_Actual,_Eq, _Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.33;
IgnitionPoint[3] = new OperationalVariable(_Actual,_Eq, _Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.44;
IgnitionPoint[4] = new OperationalVariable(_Actual,_Eq, _Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.43;
IgnitionPoint[5] = new OperationalVariable(_Actual,_Eq, _Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.17;
IgnitionPoint[6] = new OperationalVariable(_Actual,_Eq, _Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.11;
IgnitionPoint[7] = new OperationalVariable(_Actual,_Eq, _Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.77;
IgnitionPoint[8] = new OperationalVariable(_Actual,_Eq, _Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.31;
IgnitionPoint[9] = new OperationalVariable(_Actual,_Eq, _Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.13;
IgnitionPoint[10] = new OperationalVariable(_Actual,_Eq, _Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.74;
IgnitionPoint[11] = new OperationalVariable(_Actual,_Eq, _Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.47;
IgnitionPoint[12] = new OperationalVariable(_Actual,_Eq, _Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.73;
IgnitionPoint[13] = new OperationalVariable(_Actual,_Eq, _Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.37;
IgnitionPoint[14] = new OperationalVariable(_Actual,_Eq, _Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.14;
IgnitionPoint[15] = new OperationalVariable(_Actual,_Eq, _Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.41;
IgnitionPoint[16] = new OperationalVariable(_Actual,_Eq, _Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.94;
IgnitionPoint[17] = new OperationalVariable(_Actual,_Eq, _Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.82;
IgnitionPoint[18] = new OperationalVariable(_Actual,_Eq, _Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.70;
IgnitionPoint[19] = new OperationalVariable(_Actual,_Eq, _Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.68;
IgnitionPoint[20] = new OperationalVariable(_Actual,_Eq, _Speed,_MaxNoise,_NoiseOffset);
let ValveNoise=[];
_Actual=0;
_Eq=[0,250,730,1750,3390];
_Speed=0.001;
_MaxNoise=[0,40,300,1000,2500];
_NoiseOffset=0.61;
ValveNoise[1] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.58;
ValveNoise[2] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.69;
ValveNoise[3] = new OperationalVariable(_Actual,_Eq,_Speed, _MaxNoise,_NoiseOffset);
_NoiseOffset=0.67;
ValveNoise[4] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.96;
ValveNoise[5] = new OperationalVariable(_Actual,_Eq, _Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.93;
ValveNoise[6] = new OperationalVariable(_Actual,_Eq, _Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.9;
ValveNoise[7] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.87;
ValveNoise[8] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.43;
ValveNoise[9] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.13;
ValveNoise[10] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.31;
ValveNoise[11] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.11;
ValveNoise[12] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.33;
ValveNoise[13] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.44;
ValveNoise[14] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.33;
ValveNoise[15] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.08;
ValveNoise[16] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.37;
ValveNoise[17] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.19;
ValveNoise[18] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.23;
ValveNoise[19] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.74;
ValveNoise[20] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
let MinAvgMagValveNoise=[]
let ExhaustTemperatureOfCylinder=[]
_Actual=60;
_Eq=[60,86,135,336,532];
_Speed=0.01;
_MaxNoise=[16,20,30,40,60];
_NoiseOffset=0.94;
ExhaustTemperatureOfCylinder[1] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.43;
ExhaustTemperatureOfCylinder[2] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.54;
ExhaustTemperatureOfCylinder[3] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.34;
ExhaustTemperatureOfCylinder[4] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.96;
ExhaustTemperatureOfCylinder[5] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.75;
ExhaustTemperatureOfCylinder[6] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.25;
ExhaustTemperatureOfCylinder[7] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.50;
ExhaustTemperatureOfCylinder[8] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.34;
ExhaustTemperatureOfCylinder[9] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.61;
ExhaustTemperatureOfCylinder[10] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.13;
ExhaustTemperatureOfCylinder[11] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.84;
ExhaustTemperatureOfCylinder[12] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.81;
ExhaustTemperatureOfCylinder[13] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.34;
ExhaustTemperatureOfCylinder[14] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.97;
ExhaustTemperatureOfCylinder[15] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.23;
ExhaustTemperatureOfCylinder[16] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.42;
ExhaustTemperatureOfCylinder[17] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.37;
ExhaustTemperatureOfCylinder[18] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.22;
ExhaustTemperatureOfCylinder[19] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
_NoiseOffset=0.29;
ExhaustTemperatureOfCylinder[20] = new OperationalVariable(_Actual,_Eq,_Speed,_MaxNoise,_NoiseOffset);
//
let LeanoxError = 0;
let MinAvgMaxExhaustTemperatureOfCylinder=[];
let OldVelocity=0; //I will use this for the feedforward control.
let OldPower=0; //I will use this for the feedforward control.
let Aceleration=0;
let SetPointPower=new VariableParameterWithMaxSpeed(0, 707, 1.6);
let SetPointLambda=0;
let CurveLeanox1=[[30,1.5],[40,1.6]];
let CurveLeanox1Offset=0.01;
let CurveLeanox2=[];
let StartButtomPushed=false;
let IsCircuitBreakerClosed=false;
let TheCBProccessIsRequested=false;
let GridMonitoringRelayTrip=false;
let BrokenModeIsActive=false;
let xoffNoise = 0;
let StageOfOperation=0;
let Emissions={NOx:0, O2:0, CO2:0};